### ISSUE TITLE
Not all speakers show up in Home

### ISSUE THREAD

**Issue by jojost1** [SphtKr/homebridge-itunes#36]
Hi,
I've got a total of 4 speakers that should show up in HomeKit with this plugin:
- Computer (iMac)
- AirPort Express 1
- AirPort Express 2
- Apple TV 4

What shows up is only AE1 and ATV4, not the Computer or AE2. There is also no 'iTunes accessory' switch. The two that show up, seem to work: when turning one on and no music is playing, music starts playing on the correct speaker.

Will test this plugin in my other home coming week, with only one MacBook, one AirPort Express and one ATV3 to see if the same problem occurs there.

I already tried deleting the `~/.homebridge/accessories/cachedAccessories`, no success.

Any ideas?

**Comment by SphtKr** [comment]
Okay, first--I should ask--do those extra speakers show up in iTunes itself as AirPlay destinations? If not they won't show in Homebridge, because the plugin gets its info from iTunes.

Second, I've just published 0.2.0-alpha1, which lets you more granularly manage bridged devices with Hesperus. Can you update to this, and use the config GUI in Hesperus and see if you can add the missing devices there? (See the latest README.md for more info.) It's also possible that the 0.2.0-alpha1 update will resolve the issue on its own.

**Comment by jojost1** [comment]
> Okay, first--I should ask--do those extra speakers show up in iTunes itself as AirPlay destinations? If not they won't show in Homebridge, because the plugin gets its info from iTunes.

Yeah they do. I'm not in the house right now or anytime soon probably though.


> Will test this plugin in my other home coming week, with only one MacBook, one AirPort Express and one ATV3 to see if the same problem occurs there.

In my other home I installed the alpha1 and it successfully saw every device and it seems to work :-)
